### ISSUE TITLE
.Net Core2: Ninject.Extensions.Factory.FuncTests.LazyInjection fails

### ISSUE THREAD

**Issue by lsoft** [ninject/Ninject.Extensions.Factory#38]
Several constructors have the same priority.

```
Ninject.Extensions.Factory.FuncTests.LazyInjection
Error message:
 Ninject.ActivationException : Error activating Lazy{IWeapon} using implicit self-binding of Lazy{IWeapon}
Several constructors have the same priority. Please specify the constructor using ToConstructor syntax or add an Inject attribute.

Constructors:
Lazy`1(IWeapon value)
Lazy`1(Func{IWeapon} valueFactory)

Activation path:
  2) Injection of dependency Lazy{IWeapon} into parameter lazyWeapon of constructor of type ClassWithLazy
  1) Request for ClassWithLazy

Suggestions:
  1) Ensure that the implementation type has a public constructor.
  2) If you have implemented the Singleton pattern, use a binding with InSingletonScope() instead.

Трассировка стека:
   at Ninject.Infrastructure.Language.ExtensionsForIEnumerableOfT.SingleOrThrowException[T](IEnumerable`1 series, Func`1 exceptionCreator)
   at Ninject.Activation.Providers.StandardProvider.DetermineConstructorInjectionDirective(IContext context)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
   at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
   at Ninject.KernelBase.Resolve(IRequest request)
   at Ninject.Planning.Targets.Target`1.ResolveWithin(IContext parent)
   at Ninject.Activation.Providers.StandardProvider.GetValue(IContext context, ITarget target)
   at Ninject.Activation.Providers.StandardProvider.<>c__DisplayClass15_0.<Create>b__0(ITarget target)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
   at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
   at Ninject.KernelBase.Resolve(IRequest request)
   at Ninject.ResolutionExtensions.GetResolutionIterator(IResolutionRoot root, Type service, Func`2 constraint, IEnumerable`1 parameters, Boolean isOptional, Boolean isUnique)
   at Ninject.ResolutionExtensions.Get[T](IResolutionRoot root, IParameter[] parameters)
   at Ninject.Extensions.Factory.FuncTests.LazyInjection() 
```

Take a look on results of this snippet:

```
            var t = typeof(Lazy<IWeapon>);
            var cs = t.GetConstructors();

            foreach(var c in cs)
            {
                Console.WriteLine(c.ToString());
            }
```

.Net Framework:

```
Void .ctor()
Void .ctor(System.Func`1[ConsoleApplication37.IWeapon])
Void .ctor(Boolean)
Void .ctor(System.Threading.LazyThreadSafetyMode)
Void .ctor(System.Func`1[ConsoleApplication37.IWeapon], Boolean)
Void .ctor(System.Func`1[ConsoleApplication37.IWeapon], System.Threading.LazyThreadSafetyMode)

```
Total: 6

.Net Core:

```
Void .ctor()
Void .ctor(ConsoleApplication37.IWeapon)
Void .ctor(System.Func`1[ConsoleApplication37.IWeapon])
Void .ctor(Boolean)
Void .ctor(System.Threading.LazyThreadSafetyMode)
Void .ctor(System.Func`1[ConsoleApplication37.IWeapon], Boolean)
Void .ctor(System.Func`1[ConsoleApplication37.IWeapon], System.Threading.LazyThreadSafetyMode)

```
Total: 7
Extra constructor: Void .ctor(ConsoleApplication37.IWeapon)

**Comment by scott-xu** [comment]
Which runtime are you using? There are 6 constructors with .NET CORE 2.0 in windows.

**Comment by scott-xu** [comment]
Ok, I think I found it. .NET Standard 2.0 defined 6 constructors while .NET Core App 2.0 on windows has  7 constructors.

**Comment by tothdavid** [comment]
@scott-xu Unfortunatelly this fix only solves the issue when T in Lazy<T>itself is not generic. I created a pull request that handles this case as well.
